/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchStatus = IDL.Variant({
  'Matched' : IDL.Record({ 'partnerAnonId' : IDL.Text, 'sessionId' : IDL.Nat }),
  'Waiting' : IDL.Record({ 'joinedAt' : IDL.Int }),
  'NotInQueue' : IDL.Null,
  'TimedOut' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Opt(IDL.Text),
  'isOnline' : IDL.Bool,
  'anonymousId' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isGhost' : IDL.Bool,
  'receiverId' : IDL.Text,
  'timestamp' : IDL.Int,
  'ghostDeleteAt' : IDL.Opt(IDL.Int),
  'senderId' : IDL.Text,
});
export const RandomSession = IDL.Record({
  'id' : IDL.Nat,
  'startedAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'user1AnonId' : IDL.Text,
  'user2AnonId' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'isOnline' : IDL.Bool,
  'anonymousId' : IDL.Text,
});
export const RandomMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'senderAnonId' : IDL.Text,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Nat,
});
export const VoiceMessage = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'audioHash' : IDL.Text,
  'receiverId' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Text,
});

export const ListingStatus = IDL.Variant({
  'Active': IDL.Null,
  'Locked': IDL.Null,
  'Sold': IDL.Null,
  'Cancelled': IDL.Null,
});
export const TradeStatus = IDL.Variant({
  'Pending': IDL.Null,
  'PaymentSent': IDL.Null,
  'Confirmed': IDL.Null,
  'Rejected': IDL.Null,
  'Disputed': IDL.Null,
  'Cancelled': IDL.Null,
});
export const P2PListing = IDL.Record({
  'id': IDL.Nat,
  'sellerPrincipal': IDL.Principal,
  'sellerAnonId': IDL.Text,
  'listedAnonId': IDL.Text,
  'price': IDL.Text,
  'iban': IDL.Text,
  'status': ListingStatus,
  'createdAt': IDL.Int,
});
export const P2PTrade = IDL.Record({
  'id': IDL.Nat,
  'listingId': IDL.Nat,
  'buyerPrincipal': IDL.Principal,
  'buyerAnonId': IDL.Text,
  'sellerPrincipal': IDL.Principal,
  'sellerAnonId': IDL.Text,
  'listedAnonId': IDL.Text,
  'price': IDL.Text,
  'iban': IDL.Text,
  'status': TradeStatus,
  'proofScreenshotHash': IDL.Opt(IDL.Text),
  'referenceNumber': IDL.Opt(IDL.Text),
  'createdAt': IDL.Int,
  'paymentSentAt': IDL.Opt(IDL.Int),
});
export const TradeReview = IDL.Record({
  'id': IDL.Nat,
  'tradeId': IDL.Nat,
  'reviewerPrincipal': IDL.Principal,
  'targetPrincipal': IDL.Principal,
  'targetAnonId': IDL.Text,
  'stars': IDL.Nat,
  'comment': IDL.Text,
  'createdAt': IDL.Int,
});
export const TradeMessage = IDL.Record({
  'id': IDL.Nat,
  'tradeId': IDL.Nat,
  'senderPrincipal': IDL.Principal,
  'senderAnonId': IDL.Text,
  'content': IDL.Text,
  'createdAt': IDL.Int,
});
export const AdminDashboard = IDL.Record({
  'totalUsers': IDL.Nat,
  'totalTrades': IDL.Nat,
  'activeTrades': IDL.Nat,
  'completedTrades': IDL.Nat,
  'disputedTrades': IDL.Nat,
  'commissionBalance': IDL.Nat,
  'totalListings': IDL.Nat,
  'activeListings': IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Text], [], []),
  'checkMatchStatus' : IDL.Func([], [MatchStatus], ['query']),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'endRandomSession' : IDL.Func([IDL.Nat], [], []),
  'findUserByAnonId' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Text], [IDL.Vec(Message)], []),
  'getCurrentSession' : IDL.Func([], [IDL.Opt(RandomSession)], ['query']),
  'getMe' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getRandomMessages' : IDL.Func([IDL.Nat], [IDL.Vec(RandomMessage)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoiceMessages' : IDL.Func([IDL.Text], [IDL.Vec(VoiceMessage)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinMatchQueue' : IDL.Func([], [MatchStatus], []),
  'leaveMatchQueue' : IDL.Func([], [], []),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'register' : IDL.Func([], [User], []),
  'reportUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'sendRandomMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'sendVoiceMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'setOnline' : IDL.Func([IDL.Bool], [], []),
  'unblockUser' : IDL.Func([IDL.Text], [], []),
  'updateUsername' : IDL.Func([IDL.Text], [], []),
  'createListing': IDL.Func([IDL.Text, IDL.Text], [P2PListing], []),
  'getActiveListings': IDL.Func([], [IDL.Vec(P2PListing)], ['query']),
  'getMyListings': IDL.Func([], [IDL.Vec(P2PListing)], ['query']),
  'cancelListing': IDL.Func([IDL.Nat], [], []),
  'buyListing': IDL.Func([IDL.Nat], [P2PTrade], []),
  'markPaymentSent': IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'confirmTrade': IDL.Func([IDL.Nat], [], []),
  'rejectTrade': IDL.Func([IDL.Nat], [], []),
  'cancelTrade': IDL.Func([IDL.Nat], [], []),
  'getMyTrades': IDL.Func([], [IDL.Vec(P2PTrade)], ['query']),
  'getTrade': IDL.Func([IDL.Nat], [IDL.Opt(P2PTrade)], ['query']),
  'cancelExpiredTrades': IDL.Func([], [IDL.Nat], []),
  'submitTradeReview': IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [TradeReview], []),
  'getSellerReviews': IDL.Func([IDL.Text], [IDL.Vec(TradeReview)], ['query']),
  'sendTradeMessage': IDL.Func([IDL.Nat, IDL.Text], [TradeMessage], []),
  'getTradeMessages': IDL.Func([IDL.Nat], [IDL.Vec(TradeMessage)], ['query']),
  'openDispute': IDL.Func([IDL.Nat, IDL.Text], [], []),
  'resolveDispute': IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'getAllTradesAdmin': IDL.Func([], [IDL.Vec(P2PTrade)], ['query']),
  'getAllUsersAdmin': IDL.Func([], [IDL.Vec(IDL.Record({'id': IDL.Nat, 'username': IDL.Opt(IDL.Text), 'createdAt': IDL.Int, 'isOnline': IDL.Bool, 'anonymousId': IDL.Text}))], ['query']),
  'freezeUser': IDL.Func([IDL.Principal], [], []),
  'unfreezeUser': IDL.Func([IDL.Principal], [], []),
  'getAdminDashboard': IDL.Func([], [AdminDashboard], ['query']),
  'getDisputedTrades': IDL.Func([], [IDL.Vec(P2PTrade)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchStatus = IDL.Variant({
    'Matched' : IDL.Record({
      'partnerAnonId' : IDL.Text,
      'sessionId' : IDL.Nat,
    }),
    'Waiting' : IDL.Record({ 'joinedAt' : IDL.Int }),
    'NotInQueue' : IDL.Null,
    'TimedOut' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Opt(IDL.Text),
    'isOnline' : IDL.Bool,
    'anonymousId' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isGhost' : IDL.Bool,
    'receiverId' : IDL.Text,
    'timestamp' : IDL.Int,
    'ghostDeleteAt' : IDL.Opt(IDL.Int),
    'senderId' : IDL.Text,
  });
  const RandomSession = IDL.Record({
    'id' : IDL.Nat,
    'startedAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'user1AnonId' : IDL.Text,
    'user2AnonId' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'isOnline' : IDL.Bool,
    'anonymousId' : IDL.Text,
  });
  const RandomMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'senderAnonId' : IDL.Text,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Nat,
  });
  const VoiceMessage = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'audioHash' : IDL.Text,
    'receiverId' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Text,
  });
  
  const ListingStatus = IDL.Variant({
    'Active': IDL.Null,
    'Locked': IDL.Null,
    'Sold': IDL.Null,
    'Cancelled': IDL.Null,
  });
  const TradeStatus = IDL.Variant({
    'Pending': IDL.Null,
    'PaymentSent': IDL.Null,
    'Confirmed': IDL.Null,
    'Rejected': IDL.Null,
    'Disputed': IDL.Null,
    'Cancelled': IDL.Null,
  });
  const P2PListing = IDL.Record({
    'id': IDL.Nat,
    'sellerPrincipal': IDL.Principal,
    'sellerAnonId': IDL.Text,
    'listedAnonId': IDL.Text,
    'price': IDL.Text,
    'iban': IDL.Text,
    'status': ListingStatus,
    'createdAt': IDL.Int,
  });
  const P2PTrade = IDL.Record({
    'id': IDL.Nat,
    'listingId': IDL.Nat,
    'buyerPrincipal': IDL.Principal,
    'buyerAnonId': IDL.Text,
    'sellerPrincipal': IDL.Principal,
    'sellerAnonId': IDL.Text,
    'listedAnonId': IDL.Text,
    'price': IDL.Text,
    'iban': IDL.Text,
    'status': TradeStatus,
    'proofScreenshotHash': IDL.Opt(IDL.Text),
    'referenceNumber': IDL.Opt(IDL.Text),
    'createdAt': IDL.Int,
    'paymentSentAt': IDL.Opt(IDL.Int),
  });
  const TradeReview = IDL.Record({
    'id': IDL.Nat,
    'tradeId': IDL.Nat,
    'reviewerPrincipal': IDL.Principal,
    'targetPrincipal': IDL.Principal,
    'targetAnonId': IDL.Text,
    'stars': IDL.Nat,
    'comment': IDL.Text,
    'createdAt': IDL.Int,
  });
  const TradeMessage = IDL.Record({
    'id': IDL.Nat,
    'tradeId': IDL.Nat,
    'senderPrincipal': IDL.Principal,
    'senderAnonId': IDL.Text,
    'content': IDL.Text,
    'createdAt': IDL.Int,
  });
  const AdminDashboard = IDL.Record({
    'totalUsers': IDL.Nat,
    'totalTrades': IDL.Nat,
    'activeTrades': IDL.Nat,
    'completedTrades': IDL.Nat,
    'disputedTrades': IDL.Nat,
    'commissionBalance': IDL.Nat,
    'totalListings': IDL.Nat,
    'activeListings': IDL.Nat,
  });

  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Text], [], []),
    'checkMatchStatus' : IDL.Func([], [MatchStatus], ['query']),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'endRandomSession' : IDL.Func([IDL.Nat], [], []),
    'findUserByAnonId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([IDL.Text], [IDL.Vec(Message)], []),
    'getCurrentSession' : IDL.Func([], [IDL.Opt(RandomSession)], ['query']),
    'getMe' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getRandomMessages' : IDL.Func([IDL.Nat], [IDL.Vec(RandomMessage)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoiceMessages' : IDL.Func([IDL.Text], [IDL.Vec(VoiceMessage)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinMatchQueue' : IDL.Func([], [MatchStatus], []),
    'leaveMatchQueue' : IDL.Func([], [], []),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'register' : IDL.Func([], [User], []),
    'reportUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'sendRandomMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'sendVoiceMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'setOnline' : IDL.Func([IDL.Bool], [], []),
    'unblockUser' : IDL.Func([IDL.Text], [], []),
    'updateUsername' : IDL.Func([IDL.Text], [], []),
    'createListing': IDL.Func([IDL.Text, IDL.Text], [P2PListing], []),
    'getActiveListings': IDL.Func([], [IDL.Vec(P2PListing)], ['query']),
    'getMyListings': IDL.Func([], [IDL.Vec(P2PListing)], ['query']),
    'cancelListing': IDL.Func([IDL.Nat], [], []),
    'buyListing': IDL.Func([IDL.Nat], [P2PTrade], []),
    'markPaymentSent': IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'confirmTrade': IDL.Func([IDL.Nat], [], []),
    'rejectTrade': IDL.Func([IDL.Nat], [], []),
    'cancelTrade': IDL.Func([IDL.Nat], [], []),
    'getMyTrades': IDL.Func([], [IDL.Vec(P2PTrade)], ['query']),
    'getTrade': IDL.Func([IDL.Nat], [IDL.Opt(P2PTrade)], ['query']),
    'cancelExpiredTrades': IDL.Func([], [IDL.Nat], []),
    'submitTradeReview': IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [TradeReview], []),
    'getSellerReviews': IDL.Func([IDL.Text], [IDL.Vec(TradeReview)], ['query']),
    'sendTradeMessage': IDL.Func([IDL.Nat, IDL.Text], [TradeMessage], []),
    'getTradeMessages': IDL.Func([IDL.Nat], [IDL.Vec(TradeMessage)], ['query']),
    'openDispute': IDL.Func([IDL.Nat, IDL.Text], [], []),
    'resolveDispute': IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'getAllTradesAdmin': IDL.Func([], [IDL.Vec(P2PTrade)], ['query']),
    'getAllUsersAdmin': IDL.Func([], [IDL.Vec(IDL.Record({'id': IDL.Nat, 'username': IDL.Opt(IDL.Text), 'createdAt': IDL.Int, 'isOnline': IDL.Bool, 'anonymousId': IDL.Text}))], ['query']),
    'freezeUser': IDL.Func([IDL.Principal], [], []),
    'unfreezeUser': IDL.Func([IDL.Principal], [], []),
    'getAdminDashboard': IDL.Func([], [AdminDashboard], ['query']),
    'getDisputedTrades': IDL.Func([], [IDL.Vec(P2PTrade)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };