/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MatchStatus = {
    'Matched' : { 'partnerAnonId' : string, 'sessionId' : bigint }
  } |
  { 'Waiting' : { 'joinedAt' : bigint } } |
  { 'NotInQueue' : null } |
  { 'TimedOut' : null };
export interface Message {
  'id' : bigint,
  'content' : string,
  'isGhost' : boolean,
  'receiverId' : string,
  'timestamp' : bigint,
  'ghostDeleteAt' : [] | [bigint],
  'senderId' : string,
}
export interface RandomMessage {
  'id' : bigint,
  'content' : string,
  'senderAnonId' : string,
  'timestamp' : bigint,
  'sessionId' : bigint,
}
export interface RandomSession {
  'id' : bigint,
  'startedAt' : bigint,
  'isActive' : boolean,
  'user1AnonId' : string,
  'user2AnonId' : string,
}
export interface User {
  'id' : bigint,
  'username' : [] | [string],
  'createdAt' : bigint,
  'isOnline' : boolean,
  'anonymousId' : string,
}
export interface UserProfile {
  'username' : [] | [string],
  'isOnline' : boolean,
  'anonymousId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoiceMessage {
  'id' : bigint,
  'duration' : bigint,
  'audioHash' : string,
  'receiverId' : string,
  'timestamp' : bigint,
  'senderId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export type ListingStatus = { 'Active': null } | { 'Locked': null } | { 'Sold': null } | { 'Cancelled': null };
export type TradeStatus = { 'Pending': null } | { 'PaymentSent': null } | { 'Confirmed': null } | { 'Rejected': null } | { 'Disputed': null } | { 'Cancelled': null };
export interface P2PListing {
  id: bigint;
  sellerPrincipal: Principal;
  sellerAnonId: string;
  listedAnonId: string;
  price: string;
  iban: string;
  status: ListingStatus;
  createdAt: bigint;
}
export interface P2PTrade {
  id: bigint;
  listingId: bigint;
  buyerPrincipal: Principal;
  buyerAnonId: string;
  sellerPrincipal: Principal;
  sellerAnonId: string;
  listedAnonId: string;
  price: string;
  iban: string;
  status: TradeStatus;
  proofScreenshotHash: [] | [string];
  referenceNumber: [] | [string];
  createdAt: bigint;
  paymentSentAt: [] | [bigint];
}
export interface TradeReview {
  id: bigint;
  tradeId: bigint;
  reviewerPrincipal: Principal;
  targetPrincipal: Principal;
  targetAnonId: string;
  stars: bigint;
  comment: string;
  createdAt: bigint;
}
export interface TradeMessage {
  id: bigint;
  tradeId: bigint;
  senderPrincipal: Principal;
  senderAnonId: string;
  content: string;
  createdAt: bigint;
}
export interface AdminDashboard {
  totalUsers: bigint;
  totalTrades: bigint;
  activeTrades: bigint;
  completedTrades: bigint;
  disputedTrades: bigint;
  commissionBalance: bigint;
  totalListings: bigint;
  activeListings: bigint;
}

export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[string], undefined>,
  'checkMatchStatus' : ActorMethod<[], MatchStatus>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'endRandomSession' : ActorMethod<[bigint], undefined>,
  'findUserByAnonId' : ActorMethod<[string], [] | [UserProfile]>,
  'getBlockedUsers' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[string], Array<Message>>,
  'getCurrentSession' : ActorMethod<[], [] | [RandomSession]>,
  'getMe' : ActorMethod<[], [] | [User]>,
  'getRandomMessages' : ActorMethod<[bigint], Array<RandomMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoiceMessages' : ActorMethod<[string], Array<VoiceMessage>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinMatchQueue' : ActorMethod<[], MatchStatus>,
  'leaveMatchQueue' : ActorMethod<[], undefined>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'register' : ActorMethod<[], User>,
  'reportUser' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string, boolean], bigint>,
  'sendRandomMessage' : ActorMethod<[bigint, string], bigint>,
  'sendVoiceMessage' : ActorMethod<[string, string, bigint], bigint>,
  'setOnline' : ActorMethod<[boolean], undefined>,
  'unblockUser' : ActorMethod<[string], undefined>,
  'updateUsername' : ActorMethod<[string], undefined>,
  'createListing': ActorMethod<[string, string], P2PListing>;
  'getActiveListings': ActorMethod<[], Array<P2PListing>>;
  'getMyListings': ActorMethod<[], Array<P2PListing>>;
  'cancelListing': ActorMethod<[bigint], undefined>;
  'buyListing': ActorMethod<[bigint], P2PTrade>;
  'markPaymentSent': ActorMethod<[bigint, string, string], undefined>;
  'confirmTrade': ActorMethod<[bigint], undefined>;
  'rejectTrade': ActorMethod<[bigint], undefined>;
  'cancelTrade': ActorMethod<[bigint], undefined>;
  'getMyTrades': ActorMethod<[], Array<P2PTrade>>;
  'getTrade': ActorMethod<[bigint], [] | [P2PTrade]>;
  'cancelExpiredTrades': ActorMethod<[], bigint>;
  'submitTradeReview': ActorMethod<[bigint, bigint, string], TradeReview>;
  'getSellerReviews': ActorMethod<[string], Array<TradeReview>>;
  'sendTradeMessage': ActorMethod<[bigint, string], TradeMessage>;
  'getTradeMessages': ActorMethod<[bigint], Array<TradeMessage>>;
  'openDispute': ActorMethod<[bigint, string], undefined>;
  'resolveDispute': ActorMethod<[bigint, boolean], undefined>;
  'getAllTradesAdmin': ActorMethod<[], Array<P2PTrade>>;
  'getAllUsersAdmin': ActorMethod<[], Array<any>>;
  'freezeUser': ActorMethod<[Principal], undefined>;
  'unfreezeUser': ActorMethod<[Principal], undefined>;
  'getAdminDashboard': ActorMethod<[], AdminDashboard>;
  'getDisputedTrades': ActorMethod<[], Array<P2PTrade>>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];