/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MatchStatus = {
    'Matched' : { 'partnerAnonId' : string, 'sessionId' : bigint }
  } |
  { 'Waiting' : { 'joinedAt' : bigint } } |
  { 'NotInQueue' : null } |
  { 'TimedOut' : null };
export interface Message {
  'id' : bigint,
  'content' : string,
  'isGhost' : boolean,
  'receiverId' : string,
  'timestamp' : bigint,
  'ghostDeleteAt' : [] | [bigint],
  'senderId' : string,
}
export interface RandomMessage {
  'id' : bigint,
  'content' : string,
  'senderAnonId' : string,
  'timestamp' : bigint,
  'sessionId' : bigint,
}
export interface RandomSession {
  'id' : bigint,
  'startedAt' : bigint,
  'isActive' : boolean,
  'user1AnonId' : string,
  'user2AnonId' : string,
}
export interface User {
  'id' : bigint,
  'username' : [] | [string],
  'createdAt' : bigint,
  'isOnline' : boolean,
  'anonymousId' : string,
}
export interface UserProfile {
  'username' : [] | [string],
  'isOnline' : boolean,
  'anonymousId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoiceMessage {
  'id' : bigint,
  'duration' : bigint,
  'audioHash' : string,
  'receiverId' : string,
  'timestamp' : bigint,
  'senderId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[string], undefined>,
  'checkMatchStatus' : ActorMethod<[], MatchStatus>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'endRandomSession' : ActorMethod<[bigint], undefined>,
  'findUserByAnonId' : ActorMethod<[string], [] | [UserProfile]>,
  'getBlockedUsers' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[string], Array<Message>>,
  'getCurrentSession' : ActorMethod<[], [] | [RandomSession]>,
  'getMe' : ActorMethod<[], [] | [User]>,
  'getRandomMessages' : ActorMethod<[bigint], Array<RandomMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoiceMessages' : ActorMethod<[string], Array<VoiceMessage>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinMatchQueue' : ActorMethod<[], MatchStatus>,
  'leaveMatchQueue' : ActorMethod<[], undefined>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'register' : ActorMethod<[], User>,
  'reportUser' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string, boolean], bigint>,
  'sendRandomMessage' : ActorMethod<[bigint, string], bigint>,
  'sendVoiceMessage' : ActorMethod<[string, string, bigint], bigint>,
  'setOnline' : ActorMethod<[boolean], undefined>,
  'unblockUser' : ActorMethod<[string], undefined>,
  'updateUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];