/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RandomMessage {
    id: bigint;
    content: string;
    senderAnonId: string;
    timestamp: bigint;
    sessionId: bigint;
}
export interface RandomSession {
    id: bigint;
    startedAt: bigint;
    isActive: boolean;
    user1AnonId: string;
    user2AnonId: string;
}
export interface User {
    id: bigint;
    username?: string;
    createdAt: bigint;
    isOnline: boolean;
    anonymousId: string;
}
export interface VoiceMessage {
    id: bigint;
    duration: bigint;
    audioHash: string;
    receiverId: string;
    timestamp: bigint;
    senderId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Message {
    id: bigint;
    content: string;
    isGhost: boolean;
    receiverId: string;
    timestamp: bigint;
    ghostDeleteAt?: bigint;
    senderId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type MatchStatus = {
    __kind__: "Matched";
    Matched: {
        partnerAnonId: string;
        sessionId: bigint;
    };
} | {
    __kind__: "Waiting";
    Waiting: {
        joinedAt: bigint;
    };
} | {
    __kind__: "NotInQueue";
    NotInQueue: null;
} | {
    __kind__: "TimedOut";
    TimedOut: null;
};
export interface UserProfile {
    username?: string;
    isOnline: boolean;
    anonymousId: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(anonId: string): Promise<void>;
    checkMatchStatus(): Promise<MatchStatus>;
    deleteMessage(msgId: bigint): Promise<void>;
    endRandomSession(sessionId: bigint): Promise<void>;
    findUserByAnonId(anonId: string): Promise<UserProfile | null>;
    getBlockedUsers(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(otherAnonId: string): Promise<Array<Message>>;
    getCurrentSession(): Promise<RandomSession | null>;
    getMe(): Promise<User | null>;
    getRandomMessages(sessionId: bigint): Promise<Array<RandomMessage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVoiceMessages(otherAnonId: string): Promise<Array<VoiceMessage>>;
    isCallerAdmin(): Promise<boolean>;
    joinMatchQueue(): Promise<MatchStatus>;
    leaveMatchQueue(): Promise<void>;
    listUsers(): Promise<Array<User>>;
    register(): Promise<User>;
    reportUser(anonId: string, reason: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(receiverAnonId: string, content: string, isGhost: boolean): Promise<bigint>;
    sendRandomMessage(sessionId: bigint, content: string): Promise<bigint>;
    sendVoiceMessage(receiverAnonId: string, audioHash: string, duration: bigint): Promise<bigint>;
    setOnline(isOnline: boolean): Promise<void>;
    unblockUser(anonId: string): Promise<void>;
    updateUsername(username: string): Promise<void>;
}
import type { MatchStatus as _MatchStatus, Message as _Message, RandomSession as _RandomSession, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
// Helper to convert raw Candid variant to __kind__ format
function fromCandidListingStatus(v: any): any {
  if ('Active' in v) return { __kind__: 'Active', Active: null };
  if ('Locked' in v) return { __kind__: 'Locked', Locked: null };
  if ('Sold' in v) return { __kind__: 'Sold', Sold: null };
  if ('Cancelled' in v) return { __kind__: 'Cancelled', Cancelled: null };
  return v;
}
function fromCandidTradeStatus(v: any): any {
  if ('Pending' in v) return { __kind__: 'Pending', Pending: null };
  if ('PaymentSent' in v) return { __kind__: 'PaymentSent', PaymentSent: null };
  if ('Confirmed' in v) return { __kind__: 'Confirmed', Confirmed: null };
  if ('Rejected' in v) return { __kind__: 'Rejected', Rejected: null };
  if ('Disputed' in v) return { __kind__: 'Disputed', Disputed: null };
  if ('Cancelled' in v) return { __kind__: 'Cancelled', Cancelled: null };
  return v;
}
function fromCandidP2PListing(v: any): any {
  return { ...v, status: fromCandidListingStatus(v.status), proofScreenshotHash: undefined, referenceNumber: undefined };
}
function fromCandidP2PTrade(v: any): any {
  return {
    ...v,
    status: fromCandidTradeStatus(v.status),
    proofScreenshotHash: v.proofScreenshotHash?.length ? v.proofScreenshotHash[0] : undefined,
    referenceNumber: v.referenceNumber?.length ? v.referenceNumber[0] : undefined,
    paymentSentAt: v.paymentSentAt?.length ? v.paymentSentAt[0] : undefined,
  };
}

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async checkMatchStatus(): Promise<MatchStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.checkMatchStatus();
                return from_candid_MatchStatus_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkMatchStatus();
            return from_candid_MatchStatus_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMessage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async endRandomSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endRandomSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endRandomSession(arg0);
            return result;
        }
    }
    async findUserByAnonId(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findUserByAnonId(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findUserByAnonId(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedUsers(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentSession(): Promise<RandomSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentSession();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentSession();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMe(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMe();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMe();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRandomMessages(arg0: bigint): Promise<Array<RandomMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomMessages(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoiceMessages(arg0: string): Promise<Array<VoiceMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceMessages(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinMatchQueue(): Promise<MatchStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.joinMatchQueue();
                return from_candid_MatchStatus_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinMatchQueue();
            return from_candid_MatchStatus_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveMatchQueue(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveMatchQueue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveMatchQueue();
            return result;
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.register();
                return from_candid_User_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register();
            return from_candid_User_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async reportUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportUser(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async sendRandomMessage(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendRandomMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendRandomMessage(arg0, arg1);
            return result;
        }
    }
    async sendVoiceMessage(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendVoiceMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendVoiceMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async setOnline(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOnline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOnline(arg0);
            return result;
        }
    }
    async unblockUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUsername(arg0);
            return result;
        }
    }

  async createListing(price: string, iban: string): Promise<any> {
    try {
      const result = await (this.actor as any).createListing(price, iban);
      return fromCandidP2PListing(result);
    } catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getActiveListings(): Promise<any[]> {
    try {
      const result = await (this.actor as any).getActiveListings();
      return result.map(fromCandidP2PListing);
    } catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getMyListings(): Promise<any[]> {
    try {
      const result = await (this.actor as any).getMyListings();
      return result.map(fromCandidP2PListing);
    } catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async cancelListing(listingId: bigint): Promise<void> {
    try { await (this.actor as any).cancelListing(listingId); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async buyListing(listingId: bigint): Promise<any> {
    try {
      const result = await (this.actor as any).buyListing(listingId);
      return fromCandidP2PTrade(result);
    } catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async markPaymentSent(tradeId: bigint, referenceNumber: string, screenshotHash: string): Promise<void> {
    try { await (this.actor as any).markPaymentSent(tradeId, referenceNumber, screenshotHash); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async confirmTrade(tradeId: bigint): Promise<void> {
    try { await (this.actor as any).confirmTrade(tradeId); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async rejectTrade(tradeId: bigint): Promise<void> {
    try { await (this.actor as any).rejectTrade(tradeId); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async cancelTrade(tradeId: bigint): Promise<void> {
    try { await (this.actor as any).cancelTrade(tradeId); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getMyTrades(): Promise<any[]> {
    try {
      const result = await (this.actor as any).getMyTrades();
      return result.map(fromCandidP2PTrade);
    } catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getTrade(tradeId: bigint): Promise<any> {
    try {
      const result = await (this.actor as any).getTrade(tradeId);
      return result.length ? fromCandidP2PTrade(result[0]) : null;
    } catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async cancelExpiredTrades(): Promise<bigint> {
    try { return await (this.actor as any).cancelExpiredTrades(); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async submitTradeReview(tradeId: bigint, stars: bigint, comment: string): Promise<any> {
    try { return await (this.actor as any).submitTradeReview(tradeId, stars, comment); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getSellerReviews(sellerAnonId: string): Promise<any[]> {
    try { return await (this.actor as any).getSellerReviews(sellerAnonId); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async sendTradeMessage(tradeId: bigint, content: string): Promise<any> {
    try { return await (this.actor as any).sendTradeMessage(tradeId, content); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getTradeMessages(tradeId: bigint): Promise<any[]> {
    try { return await (this.actor as any).getTradeMessages(tradeId); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async openDispute(tradeId: bigint, evidence: string): Promise<void> {
    try { await (this.actor as any).openDispute(tradeId, evidence); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async resolveDispute(tradeId: bigint, favorBuyer: boolean): Promise<void> {
    try { await (this.actor as any).resolveDispute(tradeId, favorBuyer); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getAllTradesAdmin(): Promise<any[]> {
    try {
      const result = await (this.actor as any).getAllTradesAdmin();
      return result.map(fromCandidP2PTrade);
    } catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getAllUsersAdmin(): Promise<any[]> {
    try { return await (this.actor as any).getAllUsersAdmin(); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async freezeUser(target: any): Promise<void> {
    try { await (this.actor as any).freezeUser(target); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async unfreezeUser(target: any): Promise<void> {
    try { await (this.actor as any).unfreezeUser(target); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getAdminDashboard(): Promise<any> {
    try { return await (this.actor as any).getAdminDashboard(); }
    catch(e) { if (this.processError) this.processError(e); throw e; }
  }
  async getDisputedTrades(): Promise<any[]> {
    try {
      const result = await (this.actor as any).getDisputedTrades();
      return result.map(fromCandidP2PTrade);
    } catch(e) { if (this.processError) this.processError(e); throw e; }
  }
}
function from_candid_MatchStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_User_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RandomSession]): RandomSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: [] | [string];
    isOnline: boolean;
    anonymousId: string;
}): {
    username?: string;
    isOnline: boolean;
    anonymousId: string;
} {
    return {
        username: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.username)),
        isOnline: value.isOnline,
        anonymousId: value.anonymousId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    isGhost: boolean;
    receiverId: string;
    timestamp: bigint;
    ghostDeleteAt: [] | [bigint];
    senderId: string;
}): {
    id: bigint;
    content: string;
    isGhost: boolean;
    receiverId: string;
    timestamp: bigint;
    ghostDeleteAt?: bigint;
    senderId: string;
} {
    return {
        id: value.id,
        content: value.content,
        isGhost: value.isGhost,
        receiverId: value.receiverId,
        timestamp: value.timestamp,
        ghostDeleteAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.ghostDeleteAt)),
        senderId: value.senderId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    username: [] | [string];
    createdAt: bigint;
    isOnline: boolean;
    anonymousId: string;
}): {
    id: bigint;
    username?: string;
    createdAt: bigint;
    isOnline: boolean;
    anonymousId: string;
} {
    return {
        id: value.id,
        username: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.username)),
        createdAt: value.createdAt,
        isOnline: value.isOnline,
        anonymousId: value.anonymousId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Matched: {
        partnerAnonId: string;
        sessionId: bigint;
    };
} | {
    Waiting: {
        joinedAt: bigint;
    };
} | {
    NotInQueue: null;
} | {
    TimedOut: null;
}): {
    __kind__: "Matched";
    Matched: {
        partnerAnonId: string;
        sessionId: bigint;
    };
} | {
    __kind__: "Waiting";
    Waiting: {
        joinedAt: bigint;
    };
} | {
    __kind__: "NotInQueue";
    NotInQueue: null;
} | {
    __kind__: "TimedOut";
    TimedOut: null;
} {
    return "Matched" in value ? {
        __kind__: "Matched",
        Matched: value.Matched
    } : "Waiting" in value ? {
        __kind__: "Waiting",
        Waiting: value.Waiting
    } : "NotInQueue" in value ? {
        __kind__: "NotInQueue",
        NotInQueue: value.NotInQueue
    } : "TimedOut" in value ? {
        __kind__: "TimedOut",
        TimedOut: value.TimedOut
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
